### ISSUE TITLE
Learn button not working

### ISSUE THREAD

**Issue by culture4515** [jankratochvilcz/kotobaten-flutter#47]
Thanks for the great project.

Everything works smoothly except learn button. When I press learn button, it is loading forever and nothing changes.

Also I wonder how to setup the application with my own server.

Thank you

**Comment by jankratochvilcz** [comment]
Heya @culture4515, thanks for filing the ticket! Can you please send me which email you registered under to jan@kotobaten.app? I'll check out on the weekend what is the issue and hopefully provide a fix.

**Comment by culture4515** [comment]
@jankratochvilcz Thank you for the quick response. My registered email is culture4515@gmail.com. I am having the same issue on both web and mobile versions.

**Comment by jankratochvilcz** [comment]
Thanks @culture4515! I found the issue and fixed it, the fix should be live in a couple of minutes. Further bug reports would be very appreciated. I have been using the app for a few years and for that reason I don't always hit the bugs that fresh accounts will have. Please re-open the issue in case it doesn't solve it for you!

Regarding self-hosting, this is currently not possible. I do hope to open-source it in time tho', just like the flutter frontend :-) It's written in .NET and runs in a mix of Docker containers and some Azure components, so it would be a bit of work to self-host anyways (I don't have infrastructure-as-code for everything yet). Hope this makes sense!

**Comment by culture4515** [comment]
@jankratochvilcz Thank you for the quick response. But I am still having the same issue on the web. Have you updated the web version?

**Comment by jankratochvilcz** [comment]
Ah, I see there was a deployment error, can you please try in a few minutes?

**Comment by culture4515** [comment]
@jankratochvilcz Oh, thank you. It is working fine now.
